<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Plus, Trash2 } from '@lucide/vue'
import { Button } from './ui/button'
import JsonField from './JsonField.vue'
import { evaluatorDefaults, evaluatorKinds, splitList } from '@/lib/editor'
import type { Obj, Project } from '@/api/client'
const props = defineProps<{ kind: string; modelValue: Obj; project: Project; credentials: Obj[] }>()
const emit = defineEmits<{ dirty: []; validity: [key: string, valid: boolean] }>()
const d = computed(() => props.modelValue)
const evaluatorResources = computed(() => props.project.resources.filter(r => r.kind === 'evaluator'))
const chosen = (r: Obj) => r.versions.find((v: Obj) => d.value.evaluator_version_ids.includes(v.id))?.id || ''
function selectEvaluator(r: Obj, id: string) { d.value.evaluator_version_ids = d.value.evaluator_version_ids.filter((v: string) => !r.versions.some((version: Obj) => version.id === v)); if (id) d.value.evaluator_version_ids.push(id); emit('dirty') }
function changeKind(event: Event) { const select = event.target as HTMLSelectElement; if (!window.confirm('Changing evaluator type resets its specific settings. Continue?')) { select.value = d.value.kind; return }; d.value.kind = select.value; d.value.config = evaluatorDefaults(d.value.kind); d.value.definition = { value_type: 'number', direction: 'higher', aggregation: d.value.kind === 'classification' ? 'classification' : 'mean', threshold: null }; emit('dirty') }
const mappingError = ref('')
const mappingRows = ref(Object.entries(d.value.request_mapping || {}).map(([key, value]) => ({ key, value: String(value) })))
let mappingSnapshot = JSON.stringify(d.value.request_mapping || {})
watch(() => JSON.stringify(d.value.request_mapping || {}), next => {
  if (next !== mappingSnapshot) { mappingRows.value = Object.entries(d.value.request_mapping || {}).map(([key, value]) => ({ key, value: String(value) })); mappingSnapshot = next }
})
function updateMapping() {
  const keys = mappingRows.value.map(r => r.key)
  if (keys.some(k => !k.trim() || k.includes('/')) || new Set(keys).size !== keys.length) { mappingError.value = 'Request fields must be unique, nonempty names without slashes.'; emit('validity', 'mapping-key', false); return }
  mappingError.value = ''; emit('validity', 'mapping-key', true)
  const next = Object.fromEntries(mappingRows.value.map(r => [r.key, r.value]))
  mappingSnapshot = JSON.stringify(next); d.value.request_mapping = next; emit('dirty')
}
function addMapping() { let key = 'field'; let n = 1; while (mappingRows.value.some(r => r.key === key)) key = `field${n++}`; mappingRows.value.push({ key, value: '' }); updateMapping() }
function removeMapping(index: number) { mappingRows.value.splice(index, 1); updateMapping() }

function setList(key: string, event: Event) { d.value.config[key] = splitList((event.target as HTMLTextAreaElement).value) }
</script>
<template>
<div @input="emit('dirty')" @change="emit('dirty')">
  <template v-if="kind === 'target'">
    <div class="section-intro"><div><h3>HTTP connection</h3><p>Send JSON input and map the response into an evaluation result.</p></div><span class="version-badge">POST · JSON</span></div>
    <label>Endpoint URL<input v-model="d.endpoint" type="url" required placeholder="https://your-test-service.example/evaluate"/></label>
    <div class="form-grid"><label>Credential<select v-model="d.credential_id"><option :value="null">No authentication</option><option v-for="c in credentials" :key="c.id" :value="c.id">{{ c.name }} · {{ c.value }}</option></select><small>Manage encrypted credentials in Settings.</small></label><label v-if="d.credential_id">Authentication header<select v-model="d.auth_header"><option>Authorization</option><option>X-API-Key</option></select></label><label v-if="d.credential_id">Authentication prefix<input v-model="d.auth_prefix" placeholder="Bearer (followed by a space)"/></label></div>
    <div class="form-section"><div class="section-intro"><div><h3>Request mapping</h3><p>Leave this empty to send the complete input. Otherwise map top-level request fields to input paths.</p></div><Button type="button" variant="outline" size="sm" @click="addMapping"><Plus :size="14"/>Add mapping</Button></div><div v-for="(row, index) in mappingRows" :key="index" class="mapping-row"><label>Request field<input v-model="row.key" required @input="updateMapping"/></label><label>Input JSON Pointer<input v-model="row.value" placeholder="/text (empty = root)" @input="updateMapping"/></label><button type="button" class="icon-button" :aria-label="`Remove mapping ${row.key || index + 1}`" @click="removeMapping(index)"><Trash2 :size="16"/></button></div><p v-if="mappingError" class="field-error" role="alert">{{ mappingError }}</p></div>
    <label>Output JSON Pointer<input v-model="d.output_pointer" placeholder="/output"/><small>An empty pointer uses the entire response.</small></label>
    <div class="form-grid"><label>Timeout (seconds)<input v-model.number="d.timeout_seconds" type="number" min="0.1" max="120" step="0.1" required/></label><label>Maximum concurrency<input v-model.number="d.concurrency" type="number" min="1" max="16" required/></label><label>Requests per second<input v-model.number="d.requests_per_second" type="number" min="0.01" max="100" step="0.01" required/></label><label>Maximum attempts<input v-model.number="d.max_attempts" type="number" min="1" max="5" required/></label></div>
    <details><summary>Optional response mappings & revision metadata</summary><div class="form-grid"><label v-for="field in ['trace_pointer','metadata_pointer','usage_pointer','cost_pointer']" :key="field">{{ field.replace('_pointer', '').replace(/^./, c => c.toUpperCase()) }} JSON Pointer<input v-model="d[field]" placeholder="Leave empty for root"/></label><label>Application revision<input v-model="d.revision"/></label><label>Prompt version<input v-model="d.prompt_version"/></label><label>Model identifier<input v-model="d.model"/></label></div><label class="check-label"><input v-model="d.fixture" type="checkbox"/>Deterministic fixture target</label><JsonField :model-value="d.parameters || {}" @update:model-value="d.parameters = $event" label="Model parameters" object-only :rows="3" @validity="emit('validity', 'parameters', $event)"/></details>
  </template>
  <template v-else-if="kind === 'evaluator'">
    <div class="form-grid"><label>Evaluator type<select :value="d.kind" @change="changeKind"><option v-for="k in evaluatorKinds" :key="k.value" :value="k.value">{{ k.label }}</option></select><small>{{ evaluatorKinds.find(k => k.value === d.kind)?.hint }}</small></label><label>Metric key<input v-model="d.metric_key" aria-label="Metric key" aria-describedby="metric-key-hint" required/><small id="metric-key-hint">A stable identifier for comparisons and CI gates.</small></label></div>
    <div class="form-section">
      <template v-if="['exact_match', 'field_comparison'].includes(d.kind)"><label v-if="d.kind === 'field_comparison'">Field paths<textarea :value="(d.config.paths || []).join('\n')" @change="setList('paths', $event)" rows="4" placeholder="/answer&#10;/citations"/><small>One JSON Pointer per line. Missing and null remain different.</small></label><div class="check-row"><label class="check-label"><input v-model="d.config.trim" type="checkbox"/>Trim surrounding whitespace</label><label class="check-label"><input v-model="d.config.casefold" type="checkbox"/>Ignore letter case</label></div><p class="field-hint">Normalization is opt-in. Strict equality is the default.</p></template>
      <JsonField v-if="d.kind === 'json_schema'" v-model="d.config.schema" label="Output JSON Schema" hint="Use standard JSON Schema. Remote references are disabled." :rows="10" @validity="emit('validity', 'schema', $event)"/>
      <template v-if="d.kind === 'numeric_tolerance'"><label>Value JSON Pointer<input v-model="d.config.path" placeholder="Empty = root value"/></label><div class="form-grid"><label>Absolute tolerance<input v-model.number="d.config.absolute" type="number" min="0" step="any" required/></label><label>Relative tolerance<input v-model.number="d.config.relative" type="number" min="0" step="any" required/><small>0.05 means 5% of the reference value.</small></label></div></template>
      <template v-if="d.kind === 'classification'"><label>Label JSON Pointer<input v-model="d.config.path" placeholder="/category"/></label><label>Allowed labels<textarea :value="(d.config.labels || []).join('\n')" @change="setList('labels', $event)" rows="5"/><small>One label per line. Unrecognized predictions count as incorrect.</small></label></template>
      <template v-if="d.kind === 'tool_calls'"><div class="form-grid"><label>Required tools<textarea :value="(d.config.required || []).join('\n')" @change="setList('required', $event)" rows="3"/></label><label>Forbidden tools<textarea :value="(d.config.forbidden || []).join('\n')" @change="setList('forbidden', $event)" rows="3"/></label></div><label>Required tool order<textarea :value="(d.config.order || []).join('\n')" @change="setList('order', $event)" rows="3"/><small>One tool per line. Leave empty when ordering does not matter.</small></label><JsonField :model-value="d.config.arguments || {}" @update:model-value="d.config.arguments = $event" label="Argument schemas by tool name" object-only :rows="5" @validity="emit('validity', 'arguments', $event)"/></template>
      <template v-if="d.kind === 'llm_judge'"><div class="form-grid"><label>Judge mode<select v-model="d.config.mode"><option value="fixture">Deterministic fixture · no AI calls</option><option value="live">Live OpenAI judge</option></select></label><label>Rubric template<select v-model="d.config.template"><option value="correctness">Answer correctness</option><option value="context_support">Support by supplied context</option></select></label></div><div class="info-strip">{{ d.config.mode === 'fixture' ? 'Fixture mode checks strict reference equality. It does not measure model quality or interpret the rubric.' : 'Live judging calls OpenAI when an experiment runs. A human calibration review is recommended before release gates.' }}</div><label>Rubric<textarea v-model="d.config.rubric" rows="5" required/></label><label>Rubric version<input v-model="d.config.rubric_version" required placeholder="v1"/></label><div v-if="d.config.mode === 'live'" class="form-grid"><label>Judge model<input v-model="d.config.model" required placeholder="Your supported OpenAI model ID"/></label><label>Judge credential<select v-model="d.config.credential_id" required><option :value="null">Select a saved credential</option><option v-for="c in credentials" :key="c.id" :value="c.id">{{ c.name }}</option></select></label></div><details><summary>Judge parameters</summary><JsonField :model-value="d.config.parameters || {}" @update:model-value="d.config.parameters = $event" label="Judge parameters" hint="Supported keys: temperature and top_p, when supported by the chosen model." object-only :rows="3" @validity="emit('validity', 'judge-parameters', $event)"/></details></template>
    </div>
    <details><summary>Metric definition & retry policy</summary><div class="form-grid"><label>Score direction<select v-model="d.definition.direction"><option value="higher">Higher is better</option><option value="lower">Lower is better</option><option value="none">No direction</option></select></label><label>Aggregation<select v-model="d.definition.aggregation"><option value="mean">Mean score</option><option value="pass_rate">Pass rate</option><option value="classification">Classification metrics</option></select></label><label>Pass threshold override<input :value="d.definition.threshold" @input="d.definition.threshold = ($event.target as HTMLInputElement).value === '' ? null : Number(($event.target as HTMLInputElement).value)" type="number" step="any" placeholder="Use evaluator's pass decision"/></label><label>Evaluator maximum attempts<input v-model.number="d.max_attempts" type="number" min="1" max="5" required/></label></div><p class="field-hint">Retries apply to evaluator errors. A valid failing score is never retried.</p></details>
  </template>
  <template v-else-if="kind === 'suite'"><div class="section-intro"><div><h3>Choose your evaluation criteria</h3><p>Pin one version per evaluator. Different criteria need different metric keys.</p></div><span class="version-badge">{{ d.evaluator_version_ids.length }} selected</span></div><div v-if="!evaluatorResources.length" class="empty-state"><h3>Create an evaluator first</h3><p>A suite needs at least one saved evaluator version.</p></div><div v-for="r in evaluatorResources" :key="r.id" class="suite-choice" :class="{ selected: chosen(r) }"><label class="check-label"><input type="checkbox" :checked="!!chosen(r)" @change="selectEvaluator(r, ($event.target as HTMLInputElement).checked ? r.versions[0]!.id : '')"/><span><strong>{{ r.name }}</strong><small>{{ r.versions[0]?.config.metric_key }} · {{ evaluatorKinds.find(k => k.value === r.versions[0]?.config.kind)?.label }}</small></span></label><label v-if="chosen(r)">Pinned version<select :value="chosen(r)" @change="selectEvaluator(r, ($event.target as HTMLSelectElement).value)"><option v-for="v in r.versions" :key="v.id" :value="v.id">v{{ v.number }} · {{ new Date(v.created_at).toLocaleDateString() }}</option></select></label></div></template>
</div>
</template>
