import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { randomBytes } from 'node:crypto'
const root = path.resolve('../..')
const env = Object.fromEntries(fs.readFileSync(path.join(root,'.env'),'utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]))
const evidence = JSON.parse(fs.readFileSync(path.join(root,'docs/verification.json'),'utf8'))
const headers = { Origin: process.env.EVALDOCK_URL || 'http://localhost:5188', 'X-EvalDock-CSRF': '1' }
test('viewer can inspect versions and manage only read tokens; editing stays protected', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('demo@evaldock.local')
  await page.getByLabel('Password', { exact: true }).fill(env.DEMO_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project overview', exact: true })).toBeVisible()
  const me = await (await page.request.get('/api/auth/me')).json()
  const email = `ux-viewer-${Date.now()}@evaldock.local`, password = randomBytes(24).toString('hex')
  const create = await page.request.post(`/api/workspaces/${me.workspaces[0].id}/members`, { headers, data: { email, password, role: 'viewer', name: 'Temporary UX viewer' } })
  expect(create.ok()).toBeTruthy()
  fs.appendFileSync(path.join(root,'work/ux-created-viewers.txt'), `${email}\n`)
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project overview', exact: true })).toBeVisible()
  const id = evidence.integrations[0].project_id
  await page.goto(`/projects/${id}/datasets`)
  await expect(page.getByRole('button', { name: 'Create new', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Inspect versions', exact: true }).first().click()
  await expect(page.getByLabel('Target input', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Save immutable version', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(`/projects/${id}/settings`)
  await expect(page.getByRole('button', { name: 'Save credential', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add member', exact: true })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Token access' }).locator('option')).toHaveCount(1)
  await page.getByLabel('Token name').fill('Temporary read token')
  await page.getByLabel('Expires in (days)').fill('7')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByText('Copy your token now')).toBeVisible()
  const tokens = await (await page.request.get('/api/tokens')).json()
  expect(tokens[0].scopes).toEqual(['read'])
  await page.getByRole('button', { name: 'Hide token' }).click()
  await page.getByRole('button', { name: 'Revoke', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Token revoked')
  const forbidden = await page.request.post(`/api/projects/${id}/resources`, { headers, data: { name: 'Forbidden', kind: 'dataset', config: {}, cases: [{case_id:'a', input:{}}] } })
  expect(forbidden.status()).toBe(403)
})
