import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
const root = path.resolve('../..')
const env = Object.fromEntries(fs.readFileSync(path.join(root,'.env'),'utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]))
const evidence = JSON.parse(fs.readFileSync(path.join(root,'docs/verification.json'),'utf8'))

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('demo@evaldock.local')
  await page.getByLabel('Password', { exact: true }).fill(env.DEMO_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project overview', exact: true })).toBeVisible()
})

for (const integration of evidence.integrations) {
  test(`${integration.project}: compare, inspect, review, rescore, gate and launch`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', e => errors.push(e.message))
    const candidateResponse = await page.request.get(`/api/experiments/${integration.candidate}`)
    expect(candidateResponse.ok()).toBe(true)
    const candidate = await candidateResponse.json()
    await page.goto(`/projects/${integration.project_id}/compare`)
    await page.getByLabel('Baseline experiment').selectOption(integration.baseline)
    await page.getByLabel('Candidate experiment').selectOption(integration.candidate)
    await expect(page.getByRole('heading', { name: /Compare experiments/ })).toBeVisible()
    await page.getByRole('tab', { name: /Regressions/ }).click()
    await expect(page.locator('.case-item')).toHaveCount(integration.paired_counts.regressed)
    await page.locator('.case-item').first().click()
    await page.getByRole('button', { name: /Field differences/ }).click()
    await expect(page.locator('.diff-changed').first()).toBeVisible()
    await page.getByRole('button', { name: 'Output comparison', exact: true }).click()
    await expect(page.locator('.output-pane.baseline')).toBeVisible()
    await expect(page.locator('.output-pane.candidate')).toBeVisible()
    await page.getByLabel('Review note', { exact: true }).fill('Browser journey: independent review against the supplied reference.')
    await page.getByLabel('Human decision', { exact: true }).selectOption('true')
    await page.getByRole('button', { name: 'Save review', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('Automated judgment preserved')
    await page.screenshot({ path: path.join(root, `docs/${integration.project.split(' ')[0].toLowerCase()}-comparison.png`), fullPage: true })
    await page.getByRole('link', { name: 'Open case', exact: true }).click()
    await page.getByText('Execution details', { exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Attempt history', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Telemetry & provenance', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Observable tool-call trace', exact: true })).toHaveCount(0)
    await page.goto(`/experiments/${integration.candidate}`)
    await page.getByText('Run details & actions', { exact: true }).click()
    await page.getByLabel('Evaluation suite', { exact: true }).selectOption(candidate.suite_version_id)
    await page.getByRole('button', { name: 'Rescore outputs', exact: true }).click()
    await expect(page).not.toHaveURL(new RegExp(`${integration.candidate}$`))
    await expect(page.locator('.experiment-toolbar .status')).toHaveText('completed', { timeout: 90_000 })
    await expect(page.locator('.experiment-toolbar')).toContainText('Rescored outputs')
    await page.goto(`/projects/${integration.project_id}/gates`)
    await page.getByRole('combobox', { name: 'Experiment', exact: true }).selectOption(integration.candidate)
    await expect(page.getByRole('heading', { name: 'Changes needed', exact: true })).toBeVisible()
    await page.goto(`/projects/${integration.project_id}/experiments`)
    await page.getByRole('button', { name: 'New experiment', exact: true }).click()
    await page.getByLabel('Experiment name').fill(`Browser launch · ${integration.project}`)
    await page.getByLabel('Dataset version', { exact: true }).selectOption(candidate.dataset_version_id)
    await page.getByLabel('Target version', { exact: true }).selectOption(candidate.target_version_id)
    await page.getByLabel('Evaluation suite', { exact: true }).selectOption(candidate.suite_version_id)
    await page.getByRole('button', { name: 'Launch experiment', exact: true }).click()
    await expect(page.locator('.experiment-toolbar .status')).toHaveText('completed', { timeout: 90_000 })
    expect(errors).toEqual([])
  })
}

test('dataset version editor validates JSONL and preserves the original', async ({ page }) => {
  await page.goto(`/projects/${evidence.integrations[0].project_id}/datasets`)
  await page.getByRole('button', { name: 'New dataset', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill(`Browser dataset ${Date.now()}`)
  await page.getByText('Import JSONL with line-by-line validation').click()
  await page.getByLabel('JSONL content').fill('{"case_id":"a","input":{},"expected":null}\n{"case_id":"a","input":{}}')
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await expect(page.locator('details pre')).toContainText('Duplicate case_id')
  await page.getByLabel('JSONL content').fill('{"case_id":"a","input":{},"expected":null}')
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await page.getByRole('button', { name: 'Use 1 imported cases' }).click()
  await page.getByRole('button', { name: 'Save immutable version' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('status')).toContainText('Immutable version saved')
})


test('imported traces show tool evidence and keep missing output explicit', async ({ page }) => {
  const response = await page.request.get(`/api/experiments/${evidence.imported_trace.experiment_id}`)
  expect(response.ok()).toBe(true)
  const report = await response.json()
  const traced = report.executions.find((row: any) => row.case_id === 'agent-001')
  const missing = report.executions.find((row: any) => row.case_id === 'agent-003')
  expect(traced.trace.tool_calls[0].name).toBe('lookup_order')
  expect(missing.output_present).toBe(false)
  await page.goto(`/cases/${traced.id}`)
  await expect(page.getByRole('heading', { name: 'Observable tool-call trace', exact: true })).not.toBeVisible()
  await page.getByText('Execution details', { exact: true }).click()
  const details = page.locator('details').filter({ has: page.getByText('Execution details', { exact: true }) })
  await expect(details.getByRole('heading', { name: 'Observable tool-call trace', exact: true })).toBeVisible()
  await expect(details).toContainText('lookup_order')
  await expect(details).toContainText('respond')
  await page.goto(`/cases/${missing.id}`)
  const output = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Actual output', exact: true }) })
  await expect(output).toContainText('Missing output')
})
