import { test, expect, type Page } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
const root = path.resolve('../..')
const env = Object.fromEntries(fs.readFileSync(path.join(root,'.env'),'utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]))
const evidence = JSON.parse(fs.readFileSync(path.join(root,'docs/verification.json'),'utf8'))
const origin = process.env.EVALDOCK_URL || 'http://localhost:5188'
const headers = { Origin: origin, 'X-EvalDock-CSRF': '1' }

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('demo@evaldock.local')
  await page.getByLabel('Password', { exact: true }).fill(env.DEMO_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project overview', exact: true })).toBeVisible()
})
async function newProject(page: Page, name: string) {
  const me = await (await page.request.get('/api/auth/me')).json()
  const response = await page.request.post('/api/projects', { headers, data: { name: `UX verification · ${name} · ${Date.now()}`, workspace_id: me.workspaces[0].id } })
  expect(response.ok()).toBeTruthy()
  const id = (await response.json()).id as string
  fs.appendFileSync(path.join(root, 'work/ux-created-projects.txt'), `${id}\n`)
  return id
}
async function saved(page: Page) {
  await page.getByRole('button', { name: 'Save immutable version', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('status')).toContainText('Immutable version saved')
}

test('guided dataset versions, suite selection and imported run preserve null and missing', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  const id = await newProject(page, 'local workflow')
  await page.goto(`/projects/${id}/datasets`)
  await page.getByRole('button', { name: 'New dataset', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Answer cases')
  await page.getByLabel('Target input', { exact: true }).fill('{"question":"Hello"}')
  await page.getByLabel('Reference output provided', { exact: true }).check()
  await page.getByLabel('Expected output', { exact: true }).fill('{"answer":"Hello"}')
  await page.getByRole('button', { name: 'Add case', exact: true }).click()
  await expect(page.getByLabel('Reference output provided')).not.toBeChecked()
  await page.getByLabel('Case ID', { exact: true }).fill('missing-reference')
  await saved(page)
  let project = await (await page.request.get(`/api/projects/${id}`)).json()
  const version1 = project.resources[0].versions[0].id
  await page.getByRole('button', { name: 'Edit versions', exact: true }).click()
  await page.getByRole('button', { name: /missing-reference No reference/ }).click()
  await page.getByLabel('Reference output provided').check()
  await expect(page.getByLabel('Expected output', { exact: true })).toHaveValue('null')
  await saved(page)
  project = await (await page.request.get(`/api/projects/${id}`)).json()
  expect(project.resources[0].versions).toHaveLength(2)
  const original = await (await page.request.get(`/api/versions/${version1}`)).json()
  expect(original.cases[1]).not.toHaveProperty('expected')
  const latest = await (await page.request.get(`/api/versions/${project.resources[0].versions[0].id}`)).json()
  expect(latest.cases[1]).toHaveProperty('expected', null)

  await page.goto(`/projects/${id}/evaluators`)
  await page.getByRole('button', { name: 'New evaluator', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Answer equality')
  await page.getByLabel('Metric key', { exact: true }).fill('answer_match')
  await saved(page)
  await page.getByRole('button', { name: 'New suite', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Release criteria')
  await page.getByRole('checkbox', { name: /Answer equality/ }).check()
  await expect(page.getByLabel('Pinned version')).toBeVisible()
  await saved(page)
  await page.goto(`/projects/${id}/experiments`)
  await page.getByRole('button', { name: 'New experiment', exact: true }).click()
  await page.getByLabel('Experiment name').fill('Imported output verification')
  await page.getByLabel('Execution mode').selectOption('imported')
  await page.getByLabel('Imported outputs', { exact: true }).fill('[{"case_id":"case-001","output":{"answer":"Hello"}},{"case_id":"missing-reference","output":null}]')
  await expect(page.getByText(/All planned case \/ replicate pairs are covered/)).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Launch experiment', exact: true }).click()
  await expect(page.locator('.experiment-toolbar .status')).toHaveText('completed', { timeout: 90_000 })
  await expect(page.getByText('Cases passed', { exact: true }).locator('..')).toContainText('2 / 2')
  await expect(page.locator('.case-results tbody tr')).toHaveCount(2)
  const runId = page.url().split('/').at(-1)
  const report = await (await page.request.get(`/api/experiments/${runId}`)).json()
  expect(report.executions.every((e: any) => e.target_latency_ms === null && e.results[0].passed === true)).toBeTruthy()
  expect(errors).toEqual([])
})

test('invalid JSON, duplicate IDs and unsaved changes are guarded', async ({ page }) => {
  await page.goto(`/projects/${evidence.integrations[0].project_id}/datasets`)
  await page.getByRole('button', { name: 'New dataset', exact: true }).click()
  await expect(page.locator('#app')).toHaveAttribute('inert', '')
  await expect(page.locator('#app')).toHaveAttribute('aria-hidden', 'true')
  await page.getByLabel('Name', { exact: true }).fill('Uncommitted draft')
  await page.getByLabel('Target input', { exact: true }).fill('{broken')
  await expect(page.getByRole('button', { name: 'Save immutable version' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Advanced JSON' })).toBeDisabled()
  await page.getByLabel('Target input', { exact: true }).fill('{}')
  await page.getByRole('button', { name: 'Duplicate case', exact: true }).click()
  await page.getByLabel('Case ID', { exact: true }).fill('case-001')
  await expect(page.getByText('Duplicate case_id: case-001')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save immutable version' })).toBeDisabled()
  page.once('dialog', d => d.dismiss())
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('target and evaluator forms save exact configurations without making calls', async ({ page }) => {
  page.on('dialog', d => d.accept())
  const id = await newProject(page, 'configuration')
  const before = await (await page.request.get('http://localhost:8099/health')).json()
  await page.goto(`/projects/${id}/targets`)
  await page.getByRole('button', { name: 'New target', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Example adapter')
  await page.getByLabel('Endpoint URL').fill('https://example.com/evaluate')
  await page.getByRole('button', { name: 'Add mapping' }).click()
  await page.getByLabel('Request field', { exact: true }).fill('text')
  await page.getByLabel('Input JSON Pointer').fill('/question')
  await saved(page)
  await page.goto(`/projects/${id}/evaluators`)
  const kinds = ['field_comparison', 'classification', 'numeric_tolerance', 'tool_calls', 'json_schema', 'llm_judge']
  for (const kind of kinds) {
    await page.getByRole('button', { name: 'New evaluator', exact: true }).click()
    await page.getByLabel('Name', { exact: true }).fill(`Criteria ${kind}`)
    await page.getByLabel('Evaluator type').selectOption(kind)
    await page.getByLabel('Metric key', { exact: true }).fill(kind)
    if (kind === 'llm_judge') {
      await page.getByRole('combobox', { name: 'Judge mode', exact: true }).selectOption('live')
      await expect(page.getByRole('button', { name: 'Save immutable version' })).toBeDisabled()
      await page.getByRole('combobox', { name: 'Judge mode', exact: true }).selectOption('fixture')
    }
    await saved(page)
  }
  const project = await (await page.request.get(`/api/projects/${id}`)).json()
  const target = project.resources.find((r: any) => r.kind === 'target')
  expect(target.versions[0].config.request_mapping).toEqual({ text: '/question' })
  expect(project.resources.filter((r: any) => r.kind === 'evaluator')).toHaveLength(6)
  const after = await (await page.request.get('http://localhost:8099/health')).json()
  expect(after).toEqual(before)
})

test('gate form persists thresholds and protects unsaved policy', async ({ page }) => {
  const id = await newProject(page, 'gate policy')
  await page.goto(`/projects/${id}/gates`)
  await page.getByText('Edit release policy', { exact: true }).click()
  await page.getByLabel('Maximum regressions').fill('2')
  await page.getByLabel('Minimum coverage').fill('0.95')
  page.once('dialog', d => d.dismiss())
  await page.getByRole('link', { name: 'Overview', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/projects/${id}/gates$`))
  await page.getByRole('button', { name: 'Save gate policy' }).click()
  await expect(page.getByRole('status')).toContainText('Gate policy saved')
  await page.reload()
  await page.getByText('Edit release policy', { exact: true }).click()
  await expect(page.getByLabel('Maximum regressions')).toHaveValue('2')
  await expect(page.getByLabel('Minimum coverage')).toHaveValue('0.95')
})

test('responsive navigation, comparison filtering and keyboard tabs', async ({ page }) => {
  const integration = evidence.integrations[0]
  await page.goto(`/projects/${integration.project_id}/compare`)
  await page.getByLabel('Baseline experiment').selectOption(integration.baseline)
  await page.getByLabel('Candidate experiment').selectOption(integration.candidate)
  await expect(page.locator('.coverage-strip')).toContainText('48/48 scored')
  await page.getByRole('tab', { name: /All cases/ }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: /Regressions/ })).toHaveAttribute('aria-selected','true')
  await expect(page.locator('.case-item')).toHaveCount(6)
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(page.locator('.case-item')).toHaveCount(48)
  await page.screenshot({ path: path.join(root, 'docs/ux-comparison-desktop.png'), fullPage: false })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Toggle navigation' })).toBeVisible()
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.getByRole('link', { name: 'Datasets', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Datasets', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Toggle navigation' })).toHaveAttribute('aria-expanded','false')
  await page.getByRole('button', { name: 'New dataset', exact: true }).click()
  await expect(page.getByLabel('Target input', { exact: true })).toBeVisible()
  const widths = await page.evaluate(() => ({ body: document.documentElement.scrollWidth, viewport: innerWidth, dialog: document.querySelector('[role=dialog]')!.getBoundingClientRect().width }))
  expect(widths.body).toBeLessThanOrEqual(widths.viewport + 1)
  expect(widths.dialog).toBeLessThanOrEqual(widths.viewport)
  await page.screenshot({ path: path.join(root, 'docs/ux-editor-mobile.png'), fullPage: false })
})
