"""initial_schema

Revision ID: 8a8aa6e5a160
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "8a8aa6e5a160"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "api_tokens",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_api_tokens_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("digest", name=op.f("uq_api_tokens_digest")),
    )
    op.create_table(
        "memberships",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role in ('owner','editor','viewer')", name=op.f("ck_memberships_role")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_memberships_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("workspace_id", "user_id", name=op.f("uq_memberships_workspace_id")),
    )
    op.create_table(
        "projects",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("fixture", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_projects_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_projects_workspace_id")),
    )
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("digest", name=op.f("uq_sessions_digest")),
    )
    op.create_table(
        "audit_events",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_audit_events_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_events_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_project_id"), "audit_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_workspace_id"), "audit_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "ci_gates",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_ci_gates_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ci_gates")),
        sa.UniqueConstraint("project_id", name=op.f("uq_ci_gates_project_id")),
    )
    op.create_table(
        "credentials",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_credentials_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
    )
    op.create_index(op.f("ix_credentials_project_id"), "credentials", ["project_id"], unique=False)
    op.create_table(
        "resources",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind in ('dataset','target','evaluator','suite')", name=op.f("ck_resources_kind")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_resources_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("project_id", "kind", "name", name=op.f("uq_resources_project_id")),
    )
    op.create_index(op.f("ix_resources_project_id"), "resources", ["project_id"], unique=False)
    op.create_table(
        "versions",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["resources.id"], name=op.f("fk_versions_resource_id_resources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_versions")),
        sa.UniqueConstraint("resource_id", "number", name=op.f("uq_versions_resource_id")),
    )
    op.create_index(op.f("ix_versions_resource_id"), "versions", ["resource_id"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("target_version_id", sa.String(length=36), nullable=True),
        sa.Column("suite_version_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_id", sa.String(length=36), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dispatch_pending", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('queued','running','completed','partially_failed','failed','canceled')",
            name=op.f("ck_experiments_status"),
        ),
        sa.ForeignKeyConstraint(
            ["baseline_id"], ["experiments.id"], name=op.f("fk_experiments_baseline_id_experiments")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["versions.id"],
            name=op.f("fk_experiments_dataset_version_id_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["experiments.id"], name=op.f("fk_experiments_parent_id_experiments")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_experiments_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["suite_version_id"],
            ["versions.id"],
            name=op.f("fk_experiments_suite_version_id_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["versions.id"],
            name=op.f("fk_experiments_target_version_id_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    op.create_index(op.f("ix_experiments_project_id"), "experiments", ["project_id"], unique=False)
    op.create_table(
        "target_throttles",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["versions.id"], name=op.f("fk_target_throttles_version_id_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_throttles")),
        sa.UniqueConstraint("version_id", name=op.f("uq_target_throttles_version_id")),
    )
    op.create_table(
        "test_cases",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["versions.id"], name=op.f("fk_test_cases_version_id_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
        sa.UniqueConstraint("version_id", "case_id", name=op.f("uq_test_cases_version_id")),
    )
    op.create_index(op.f("ix_test_cases_version_id"), "test_cases", ["version_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("storage_key", sa.String(length=120), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_artifacts_experiment_id_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_artifacts_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_table(
        "baselines",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_baselines_experiment_id_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_baselines_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baselines")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_baselines_project_id")),
    )
    op.create_table(
        "comparisons",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"], ["experiments.id"], name=op.f("fk_comparisons_baseline_id_experiments")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["experiments.id"],
            name=op.f("fk_comparisons_candidate_id_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_comparisons_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparisons")),
    )
    op.create_table(
        "executions",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=160), nullable=False),
        sa.Column("replicate", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "output", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("output_present", sa.Boolean(), nullable=False),
        sa.Column(
            "trace", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_latency_ms", sa.Float(), nullable=True),
        sa.Column("evaluation_latency_ms", sa.Float(), nullable=True),
        sa.Column("target_error", sa.Text(), nullable=True),
        sa.Column("late_completion", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_executions_experiment_id_experiments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint(
            "experiment_id", "case_id", "replicate", name=op.f("uq_executions_experiment_id")
        ),
    )
    op.create_index(
        op.f("ix_executions_experiment_id"), "executions", ["experiment_id"], unique=False
    )
    op.create_table(
        "progress_events",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_progress_events_experiment_id_experiments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_events")),
    )
    op.create_index(
        op.f("ix_progress_events_experiment_id"), "progress_events", ["experiment_id"], unique=False
    )
    op.create_table(
        "attempts",
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("evaluator_version_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], name=op.f("fk_attempts_execution_id_executions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint(
            "execution_id",
            "phase",
            "evaluator_version_id",
            "number",
            name=op.f("uq_attempts_execution_id"),
        ),
    )
    op.create_index(op.f("ix_attempts_execution_id"), "attempts", ["execution_id"], unique=False)
    op.create_table(
        "evaluator_results",
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("evaluator_version_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=200), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluator_version_id"],
            ["versions.id"],
            name=op.f("fk_evaluator_results_evaluator_version_id_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_evaluator_results_execution_id_executions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluator_results")),
        sa.UniqueConstraint(
            "execution_id",
            "evaluator_version_id",
            "metric_key",
            name=op.f("uq_evaluator_results_execution_id"),
        ),
    )
    op.create_index(
        op.f("ix_evaluator_results_execution_id"),
        "evaluator_results",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "human_reviews",
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=200), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_human_reviews_execution_id_executions"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_human_reviews_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_reviews")),
    )
    op.create_index(
        op.f("ix_human_reviews_execution_id"), "human_reviews", ["execution_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_reviews_execution_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_index(op.f("ix_evaluator_results_execution_id"), table_name="evaluator_results")
    op.drop_table("evaluator_results")
    op.drop_index(op.f("ix_attempts_execution_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(op.f("ix_progress_events_experiment_id"), table_name="progress_events")
    op.drop_table("progress_events")
    op.drop_index(op.f("ix_executions_experiment_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_table("comparisons")
    op.drop_table("baselines")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_test_cases_version_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_table("target_throttles")
    op.drop_index(op.f("ix_experiments_project_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_versions_resource_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_index(op.f("ix_resources_project_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_credentials_project_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_table("ci_gates")
    op.drop_index(op.f("ix_audit_events_workspace_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_project_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("memberships")
    op.drop_table("api_tokens")
    op.drop_table("workspaces")
    op.drop_table("users")
    # ### end Alembic commands ###
