<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { ArrowRight, ArrowUpRight, ArrowUp, ArrowDown, Minus, Search, Download, GitCompareArrows, ChevronRight, Check, AlertCircle, X } from '@lucide/vue'
import { api, post, percent, ms, type Project, type Comparison, type Pair } from '@/api/client'
import { jsonDiff } from '@/lib/diff'
import { Button } from '@/components/ui/button'
import JsonView from '@/components/JsonView.vue'
import Status from '@/components/Status.vue'
const route = useRoute(), cache = useQueryClient()
const projectId = String(route.params.projectId)
const project = useQuery({ queryKey: ['project', projectId], queryFn: () => api<Project>(`/projects/${projectId}`) })
const baseline = ref(''), candidate = ref(''), metric = ref('field_accuracy'), state = ref('all'), tag = ref(''), slice = ref(''), search = ref(''), selectedKey = ref('')
const reviewNote = ref(''), reviewPassed = ref(false), notice = ref(''), error = ref(''), busy = ref(false), showReference = ref(true), tab = ref('output')
const comparison = useQuery({ queryKey: computed(() => ['comparison', baseline.value, candidate.value, metric.value, tag.value, slice.value]), queryFn: () => api<Comparison>(`/compare?baseline=${baseline.value}&candidate=${candidate.value}&metric=${encodeURIComponent(metric.value)}&tag=${encodeURIComponent(tag.value)}&slice=${encodeURIComponent(slice.value)}`), enabled: computed(() => !!baseline.value && !!candidate.value), refetchInterval: 5000 })
const experiments = computed(() => project.data.value?.experiments.filter(e => ['completed','partially_failed','failed','canceled'].includes(e.status)) || [])
const metrics = computed(() => [...new Set(project.data.value?.resources.filter(r => r.kind === 'evaluator').flatMap(r => r.versions.map(v => v.config.metric_key as string)) || [])])
watch(() => project.data.value, p => { if (p) { baseline.value ||= p.baselines.find(b => b.name === 'main')?.experiment_id || experiments.value.find(e => e.name.toLowerCase().includes('baseline'))?.id || experiments.value.at(-1)?.id || ''; candidate.value ||= experiments.value.find(e => e.id !== baseline.value && e.name.toLowerCase().includes('candidate') && e.mode === 'http')?.id || experiments.value.find(e => e.id !== baseline.value)?.id || '' } }, { immediate: true })
const rows = computed(() => comparison.data.value?.rows.filter(r => (state.value === 'all' || r.state === state.value) && (!search.value || r.case_id.toLowerCase().includes(search.value.toLowerCase()))) || [])
const selected = computed(() => rows.value.find(r => `${r.case_id}:${r.replicate}` === selectedKey.value) || rows.value[0])
const tags = computed(() => [...new Set(comparison.data.value?.rows.flatMap(r => r.candidate.case.tags || []) || [])] as string[])
const counts = computed(() => comparison.data.value?.counts || {})
const diffs = computed(() => selected.value ? jsonDiff(selected.value.baseline.output, selected.value.candidate.output) : [])
const sides = ['baseline','candidate'] as const
const tabs = [{ key: 'all', label: 'All cases' }, { key: 'regressed', label: 'Regressions' }, { key: 'improved', label: 'Improvements' }, { key: 'unscored_or_error', label: 'Errors / unscored' }]
function score(side: 'baseline' | 'candidate') { const values = comparison.data.value?.rows.map(r => r[side].results.find(e => e.metric_key === metric.value)).filter(r => r?.status === 'scored' && r.score != null).map(r => r!.score!) || []; return values.length ? values.reduce((a,b) => a+b,0) / values.length : null }
function choose(row: Pair) { selectedKey.value = `${row.case_id}:${row.replicate}`; reviewNote.value = '' }
async function saveReview() { if (!selected.value) return; busy.value = true; error.value = ''; try { await post(`/executions/${selected.value.candidate.id}/reviews`, { metric_key: metric.value, passed: reviewPassed.value, note: reviewNote.value }); notice.value = 'Human assessment saved. Automated judgment preserved.'; reviewNote.value = ''; await cache.invalidateQueries() } catch (e) { error.value = (e as Error).message } finally { busy.value = false } }
async function saveComparison() { try { await post('/comparisons', { baseline_id: baseline.value, candidate_id: candidate.value, metric: metric.value }); notice.value = 'Comparison saved with fixed experiment references.' } catch(e) { error.value = (e as Error).message } }
</script>
<template>
<main class="content compare-content">
  <div class="page-heading"><div><div class="eyebrow">EVIDENCE BEFORE DEPLOYMENT</div><h1>Compare experiments <span class="title-tag">{{ project.data.value?.name }}</span></h1><p>The whole picture. Every improvement, every regression, every case.</p></div><Button variant="outline" :disabled="!comparison.data.value" @click="saveComparison"><GitCompareArrows :size="16"/>Save comparison</Button></div>
  <div v-if="error || comparison.error.value" class="error" role="alert">{{ error || comparison.error.value?.message }}</div><div v-if="notice" class="notice" role="status"><Check :size="15"/>{{ notice }}<button aria-label="Dismiss notification" @click="notice = ''"><X :size="14"/></button></div>
  <section class="compare-selectors"><label><span class="eyebrow">BASELINE <span class="version-badge">REFERENCE</span></span><select v-model="baseline" aria-label="Baseline experiment"><option value="" disabled>Select baseline</option><option v-for="e in experiments" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><div class="versus"><ArrowRight :size="21"/></div><label><span class="eyebrow">CANDIDATE <span class="candidate-label">CHANGE</span></span><select v-model="candidate" aria-label="Candidate experiment"><option value="" disabled>Select candidate</option><option v-for="e in experiments" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><div class="selector-divider"></div><label class="metric-select"><span class="eyebrow">EVALUATION CRITERION</span><select v-model="metric" aria-label="Comparison metric"><option v-for="m in metrics" :key="m">{{ m }}</option></select></label></section>
  <div v-if="comparison.data.value?.warning" class="warning-strip"><AlertCircle :size="16"/>{{ comparison.data.value.warning }} · {{ comparison.data.value.added.length }} added · {{ comparison.data.value.removed.length }} removed · {{ comparison.data.value.changed.length }} changed</div>
  <div v-if="!baseline || !candidate" class="empty-state panel"><GitCompareArrows :size="32"/><h3>Two experiments. One clear comparison.</h3><p>Run a baseline and candidate using the same dataset, then select them above.</p><RouterLink :to="`/projects/${projectId}/experiments`" class="text-link">Go to experiments <ArrowRight :size="15"/></RouterLink></div>
  <div v-else-if="comparison.isPending.value" class="empty-state"><h3>Pairing saved case results…</h3></div>
  <template v-else-if="comparison.data.value">
    <div class="comparison-stats"><article class="comparison-stat main-stat"><span>Mean {{ metric.replaceAll('_',' ') }}</span><div><strong>{{ percent(score('baseline')) }}</strong><ArrowRight :size="19"/><strong class="green-text">{{ percent(score('candidate')) }}</strong></div><small>{{ comparison.data.value.paired_count }} compatible case / replicate pairs · scored values only</small></article><article class="comparison-stat"><span><ArrowUp :size="14"/>Improved</span><strong class="green-text">{{ counts.improved || 0 }}</strong><small>Fail → pass</small></article><article class="comparison-stat"><span><ArrowDown :size="14"/>Regressed</span><strong class="red-text">{{ counts.regressed || 0 }}</strong><small>Pass → fail</small></article><article class="comparison-stat"><span><Minus :size="14"/>Unchanged</span><strong>{{ (counts.unchanged_pass || 0) + (counts.unchanged_fail || 0) }}</strong><small>{{ counts.unchanged_pass || 0 }} pass · {{ counts.unchanged_fail || 0 }} fail</small></article><article class="comparison-stat"><span><AlertCircle :size="14"/>Unscored</span><strong>{{ counts.unscored_or_error || 0 }}</strong><small>Errors remain visible</small></article></div>
    <div class="comparison-meta"><span><span class="live-dot"></span>{{ comparison.data.value.same_dataset ? 'Same dataset version' : 'Compatible shared cases only' }}</span><span>Paired score Δ: {{ comparison.data.value.delta.mean == null ? '—' : percent(comparison.data.value.delta.mean) }} · σ {{ comparison.data.value.delta.stddev?.toFixed(3) ?? '—' }} · n={{ comparison.data.value.delta.n }}</span><span>No significance claim</span><span class="spacer"></span><span v-if="project.data.value?.fixture" class="fixture-chip">Deterministic fixtures</span></div>
    <section class="comparison-workspace"><div class="comparison-filterbar"><div class="tab-bar" role="tablist" aria-label="Result filter"><button v-for="t in tabs" :key="t.key" role="tab" :aria-selected="state === t.key" :class="{ active: state === t.key }" @click="state = t.key">{{ t.label }}<span>{{ t.key === 'all' ? comparison.data.value.paired_count : counts[t.key] || 0 }}</span></button></div><select v-model="tag" aria-label="Filter by tag"><option value="">All tags</option><option v-for="t in tags" :key="t">{{ t }}</option></select><input v-model="slice" aria-label="Filter by slice" placeholder="slice=value" class="slice-input"/></div>
      <div class="comparison-body"><aside class="case-list"><div class="case-search"><Search :size="15"/><input v-model="search" aria-label="Search cases" placeholder="Find a case…"/></div><div class="case-list-heading"><span>CASE / REPLICATE</span><span>{{ rows.length }}</span></div><button v-for="row in rows" :key="`${row.case_id}:${row.replicate}`" class="case-item" :class="{ selected: selected === row }" @click="choose(row)"><div><strong class="mono">{{ row.case_id }}</strong><small>#{{ row.replicate }}</small><ChevronRight :size="14"/></div><span class="case-state" :class="row.state"><ArrowDown v-if="row.state === 'regressed'" :size="13"/><ArrowUp v-else-if="row.state === 'improved'" :size="13"/><Minus v-else :size="13"/>{{ row.state.replaceAll('_',' ') }}</span><span v-if="row.candidate.case.tags?.includes('critical')" class="critical-dot" title="Critical case"></span></button><div v-if="!rows.length" class="empty-state"><p>No cases match these filters.</p></div></aside>
        <article v-if="selected" class="case-evidence"><div class="evidence-header"><div><span class="eyebrow">CASE EVIDENCE</span><h2>{{ selected.case_id }} <span class="replicate-label">replicate {{ selected.replicate }}</span></h2><div class="tags"><span v-for="t in selected.candidate.case.tags" :key="t">{{ t }}</span></div></div><div><Status :value="selected.state"/><RouterLink :to="`/cases/${selected.candidate.id}`" class="text-link">Open case <ArrowUpRight :size="14"/></RouterLink></div></div>
          <div class="evidence-tabs"><button :class="{ active: tab === 'output' }" @click="tab = 'output'">Output comparison</button><button :class="{ active: tab === 'diff' }" @click="tab = 'diff'">Field differences <span>{{ diffs.filter(d => d.changed).length }}</span></button><button :class="{ active: tab === 'trace' }" @click="tab = 'trace'">Observable traces</button></div>
          <div v-if="tab !== 'diff'" class="output-grid"><section v-for="side in sides" :key="side" class="output-pane" :class="side"><div class="output-heading"><span>{{ side.toUpperCase() }}</span><Status :value="selected[side].results.find(r => r.metric_key === metric)?.status !== 'scored' ? 'unscored' : selected[side].results.find(r => r.metric_key === metric)?.passed ? 'pass' : 'fail'"/></div><JsonView :value="tab === 'trace' ? selected[side].trace : selected[side].output" :missing="tab === 'output' && !selected[side].output_present"/><div v-if="selected[side].target_error" class="error">{{ selected[side].target_error }}</div><div class="output-telemetry"><span>Latency <strong>{{ ms(selected[side].target_latency_ms) }}</strong></span><span>Cost <strong>{{ selected[side].metadata.target_cost == null ? 'Unavailable' : `$${selected[side].metadata.target_cost}` }}</strong><small>{{ selected[side].metadata.target_cost_provenance || 'Not reported' }}</small></span></div></section></div>
          <div v-else class="diff-panel"><table><thead><tr><th>JSON Pointer</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody><tr v-for="diff in diffs" :key="diff.path" :class="{ 'diff-changed': diff.changed }"><td class="mono">{{ diff.path }}</td><td class="mono">{{ diff.beforeMissing ? '∅ missing' : JSON.stringify(diff.before) }}</td><td class="mono">{{ diff.afterMissing ? '∅ missing' : JSON.stringify(diff.after) }}</td></tr></tbody></table></div>
          <div class="reference-toggle"><button @click="showReference = !showReference"><ChevronRight :size="14" :class="{ rotated: showReference }"/>Reference & evaluator-only context</button><small>Never sent to the target</small></div><div v-if="showReference" class="reference-grid"><div><small>EXPECTED OUTPUT</small><JsonView :value="selected.candidate.case.expected" :missing="!('expected' in selected.candidate.case)" compact/></div><div><small>TARGET INPUT & CONTEXT</small><JsonView :value="{ input: selected.candidate.case.input, context: selected.candidate.case.context, criteria: selected.candidate.case.acceptance_criteria }" compact/></div></div>
          <div class="criterion-header"><h3>Evaluator findings</h3><span>Candidate · versioned criteria</span></div><div v-for="r in selected.candidate.results" :key="r.metric_key" class="evaluator-row"><div><strong class="mono">{{ r.metric_key }}</strong><p>{{ r.explanation }}</p><small v-if="r.evidence.length" class="mono">Evidence: {{ r.evidence.join(', ') }}</small></div><Status :value="r.status !== 'scored' ? r.status : r.passed ? 'pass' : 'fail'"/></div>
          <div class="review-inline"><div><h3>Make the human call</h3><p>Your assessment is stored alongside the automated judgment.</p><span v-if="selected.candidate.reviews.length" class="green-text">{{ selected.candidate.reviews.length }} assessment(s) saved</span></div><form @submit.prevent="saveReview"><label class="sr-only" for="review-decision">Human decision</label><select id="review-decision" v-model="reviewPassed"><option :value="false">Fail</option><option :value="true">Pass</option></select><label class="sr-only" for="review-note">Review note</label><input id="review-note" v-model="reviewNote" placeholder="Add an evidence-based review note…" required/><Button type="submit" :disabled="busy">Save review</Button></form></div>
        </article><div v-else class="empty-state"><h3>Select a case to inspect the evidence</h3></div>
      </div>
    </section><div class="comparison-footnote"><span>Latency comparability: {{ comparison.data.value.latency_comparable ? 'matching run settings' : 'unavailable or settings differ' }}. P95 uses nearest rank; see experiment reports for n.</span><a :href="`/api/experiments/${candidate}/report?format=json&metric=${metric}`" class="text-link"><Download :size="14"/>Export candidate report</a></div>
  </template>
</main>
</template>
