<script setup lang="ts">
import { computed, inject, nextTick, onBeforeUnmount, ref, watch, type Ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { useRoute, useRouter } from 'vue-router'
import { ArrowUpRight, ArrowRight, Plus, Play, Database, FlaskConical, GitCompareArrows, Download, RotateCcw, X, Check, ShieldCheck, Pin } from '@lucide/vue'
import { api, post, percent, ms, pretty, human, type Project, type Report, type Execution, type Resource, type Version, type Obj } from '@/api/client'
import { Button } from '@/components/ui/button'
import JsonView from '@/components/JsonView.vue'
import Status from '@/components/Status.vue'
const route = useRoute(), router = useRouter(), cache = useQueryClient()
const currentProject = inject<Ref<string>>('projectId')!
const page = computed(() => route.params.executionId ? 'case' : route.params.experimentId ? 'results' : String(route.params.page || 'overview'))
const experimentId = computed(() => String(route.params.experimentId || ''))
const experiment = useQuery({ queryKey: computed(() => ['experiment', experimentId.value]), queryFn: () => api<Report>(`/experiments/${experimentId.value}`), enabled: computed(() => !!experimentId.value), refetchInterval: 2500 })
const projectId = computed(() => experimentId.value ? experiment.data.value?.project_id || '' : currentProject.value)
const project = useQuery({ queryKey: computed(() => ['project', projectId.value]), queryFn: () => api<Project>(`/projects/${projectId.value}`), enabled: computed(() => !!projectId.value), refetchInterval: 4000 })
const selectedVersion = ref(''), selectedResource = ref<Resource | null>(null)
const version = useQuery({ queryKey: computed(() => ['version', selectedVersion.value]), queryFn: () => api<Version & { cases: Obj[]; resource: Resource }>(`/versions/${selectedVersion.value}`), enabled: computed(() => !!selectedVersion.value) })
const execution = useQuery({ queryKey: computed(() => ['execution', route.params.executionId]), queryFn: () => api<Execution>(`/executions/${route.params.executionId}`), enabled: computed(() => !!route.params.executionId) })
const reviewQueue = useQuery({ queryKey: computed(() => ['reviews', projectId.value]), queryFn: () => api<Execution[]>(`/projects/${projectId.value}/reviews`), enabled: computed(() => page.value === 'reviews' && !!projectId.value) })
const gateConfig = useQuery({ queryKey: computed(() => ['gate-config', projectId.value]), queryFn: () => api<Obj>(`/projects/${projectId.value}/gate`), enabled: computed(() => page.value === 'gates' && !!projectId.value) })
const settingsData = useQuery({ queryKey: computed(() => ['settings', projectId.value]), queryFn: async () => ({ credentials: await api<Obj[]>(`/projects/${projectId.value}/credentials`), tokens: await api<Obj[]>('/tokens'), audit: await api<Obj[]>(`/projects/${projectId.value}/audit`), members: await api<Obj[]>(`/workspaces/${project.data.value?.workspace_id}/members`) }), enabled: computed(() => page.value === 'settings' && !!project.data.value) })
const resources = (kind: string) => project.data.value?.resources.filter(r => r.kind === kind) || []
const versions = (kind: string) => resources(kind).flatMap(r => r.versions.map(v => ({ ...v, label: `${r.name} · v${v.number}` })))
const titles: Record<string,string> = { overview: 'Project overview', datasets: 'Datasets', targets: 'Targets', evaluators: 'Evaluators & suites', experiments: 'Experiments', reviews: 'Human review', gates: 'CI gates & reports', settings: 'Project settings' }
const title = computed(() => page.value === 'results' ? experiment.data.value?.name || 'Experiment results' : page.value === 'case' ? execution.data.value?.case_id || 'Case detail' : titles[page.value])
const notice = ref(''), error = ref(''), busy = ref(false), modal = ref(''), editor = ref(''), formName = ref(''), editorKind = ref('dataset'), importText = ref(''), preview = ref<Obj | null>(null)
const datasetId = ref(''), targetId = ref(''), suiteId = ref(''), launchMode = ref('http'), repetitions = ref(1), concurrency = ref(2), budget = ref<number>(), launchName = ref(''), imported = ref('[]')
const gateText = ref(''), gateExperiment = ref(''), metric = ref('field_accuracy'), gateResult = ref<Obj | null>(null)
const reviewMetric = ref(''), reviewNote = ref(''), reviewPassed = ref(false), onlyUnreviewed = ref(true)
const secretName = ref(''), secretValue = ref(''), tokenName = ref('CI pipeline'), newToken = ref(''), member = ref({ email: '', name: '', password: '', role: 'viewer' })
const testInput = ref('{}'), testResult = ref<Obj | null>(null), filter = ref('all')
const latestId = computed(() => project.data.value?.experiments.find(e => e.status === 'completed')?.id || '')
const latest = useQuery({ queryKey: computed(() => ['latest', latestId.value]), queryFn: () => api<Report>(`/experiments/${latestId.value}`), enabled: computed(() => page.value === 'overview' && !!latestId.value) })
const queryError = computed(() => [project.error.value, experiment.error.value, execution.error.value, version.error.value, reviewQueue.error.value, gateConfig.error.value, settingsData.error.value].find(Boolean))
const displayReviews = computed(() => reviewQueue.data.value?.filter(r => !onlyUnreviewed.value || !r.reviews.length) || [])
const filteredRows = computed(() => experiment.data.value?.executions.filter(r => filter.value === 'all' || (filter.value === 'failing' ? r.results.some(e => e.passed === false) : r.status !== 'completed')) || [])
let formProject = ''
watch(() => project.data.value, p => { if (p) { if (formProject !== p.id) { datasetId.value = ''; targetId.value = ''; suiteId.value = ''; gateExperiment.value = ''; formProject = p.id }; datasetId.value ||= versions('dataset')[0]?.id || ''; targetId.value ||= versions('target')[0]?.id || ''; suiteId.value ||= versions('suite').find(v => v.label.includes('Release'))?.id || versions('suite')[0]?.id || ''; gateExperiment.value ||= p.experiments[0]?.id || '' } }, { immediate: true })
let previousFocus: HTMLElement | null = null
function trapFocus(event: KeyboardEvent) {
  if (!modal.value || event.key !== 'Tab') return
  const elements = [...document.querySelectorAll<HTMLElement>('[role="dialog"] button:not(:disabled), [role="dialog"] input:not(:disabled), [role="dialog"] select:not(:disabled), [role="dialog"] textarea:not(:disabled), [role="dialog"] summary')].filter(e => e.offsetParent !== null)
  const first = elements[0], last = elements.at(-1)
  if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() }
  else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() }
}
watch(modal, async value => { if (value) { previousFocus = document.activeElement as HTMLElement; await nextTick(); document.querySelector<HTMLElement>('[role="dialog"] input, [role="dialog"] button')?.focus(); document.addEventListener('keydown', trapFocus) } else { document.removeEventListener('keydown', trapFocus); previousFocus?.focus() } })
onBeforeUnmount(() => document.removeEventListener('keydown', trapFocus))
watch(() => gateConfig.data.value, v => { if (v) gateText.value = pretty(v) }, { immediate: true })
watch(() => version.data.value, v => { if (v) editor.value = pretty(v.resource.kind === 'dataset' ? { config: v.config, cases: v.cases } : v.config) })
watch(() => execution.data.value, v => { if (v) reviewMetric.value = v.results[0]?.metric_key || '' })
async function action(fn: () => Promise<unknown>, message = 'Saved') { busy.value = true; error.value = ''; try { await fn(); notice.value = message; await cache.invalidateQueries() } catch (e) { error.value = (e as Error).message } finally { busy.value = false } }
function openCreate(kind: string) {
  selectedResource.value = null; selectedVersion.value = ''; editorKind.value = kind; formName.value = ''; preview.value = null; importText.value = ''
  const defaults: Record<string,unknown> = { dataset: { config: { held_out: true }, cases: [{ case_id: 'case-001', input: {}, expected: null, tags: [] }] }, target: { endpoint: 'https://your-test-service.example/evaluate', request_mapping: {}, output_pointer: '/output', timeout_seconds: 20, concurrency: 4, requests_per_second: 5 }, evaluator: { kind: 'exact_match', metric_key: 'exact_match', definition: { direction: 'higher', aggregation: 'mean' }, config: { trim: false, casefold: false } }, suite: { evaluator_version_ids: versions('evaluator').map(v => v.id) } }
  editor.value = pretty(defaults[kind]); modal.value = 'resource'
}
function openEdit(r: Resource) { selectedResource.value = r; selectedVersion.value = r.versions[0]!.id; editorKind.value = r.kind; formName.value = r.name; const cached = version.data.value; editor.value = cached?.id === selectedVersion.value ? pretty(r.kind === 'dataset' ? { config: cached.config, cases: cached.cases } : cached.config) : r.kind === 'dataset' ? '' : pretty(r.versions[0]!.config); modal.value = 'resource' }
async function saveResource() { await action(async () => { const parsed = JSON.parse(editor.value); const payload = editorKind.value === 'dataset' ? parsed : { config: parsed }; if (selectedResource.value) await post(`/resources/${selectedResource.value.id}/versions`, payload); else await post(`/projects/${projectId.value}/resources`, { kind: editorKind.value, name: formName.value, ...payload }); modal.value = '' }, 'Immutable version saved') }
async function previewImport() { await action(async () => { preview.value = await post<Obj>('/datasets/preview', { content: importText.value }); if (preview.value.valid) editor.value = pretty({ config: { held_out: true }, cases: preview.value.cases }) }, 'Import validated') }
async function launchExperiment() { await action(async () => { const result = await post<Report>(`/projects/${projectId.value}/experiments`, { name: launchName.value || `Experiment ${new Date().toLocaleString()}`, dataset_version_id: datasetId.value, target_version_id: launchMode.value === 'http' ? targetId.value : null, suite_version_id: suiteId.value, repetitions: Number(repetitions.value), concurrency: Number(concurrency.value), mode: launchMode.value, imports: launchMode.value === 'imported' ? JSON.parse(imported.value) : [], import_dataset_version_id: launchMode.value === 'imported' ? datasetId.value : null, max_target_calls: budget.value || null }); modal.value = ''; router.push(`/experiments/${result.id}`) }, 'Experiment queued') }
async function rescore() { await action(async () => { const e = experiment.data.value!; const r = await post<Report>(`/experiments/${e.id}/rescore`, { suite_version_id: suiteId.value || e.suite_version_id, name: `${e.name} · rescore` }); router.push(`/experiments/${r.id}`) }, 'Saved outputs queued for rescoring') }
async function saveReview() { await action(async () => { await post(`/executions/${route.params.executionId}/reviews`, { metric_key: reviewMetric.value, passed: reviewPassed.value, note: reviewNote.value }); reviewNote.value = '' }, 'Human assessment saved; automated result preserved') }
async function createSecret() { await action(async () => { await post(`/projects/${projectId.value}/credentials`, { name: secretName.value, value: secretValue.value }); secretValue.value = '' }, 'Encrypted credential saved') }
async function createToken() { await action(async () => { const r = await post<Obj>('/tokens', { workspace_id: project.data.value?.workspace_id, name: tokenName.value, scopes: ['read','write'] }); newToken.value = r.token }, 'Token created; copy it now') }
</script>
<template>
<main class="content">
  <div class="page-heading"><div><div class="eyebrow">{{ project.data.value?.name || 'EVALUATION WORKBENCH' }}</div><h1>{{ title }}</h1><p>Version your evidence. Understand the change. Make a confident release decision.</p></div><div class="heading-actions"><span v-if="project.data.value?.fixture" class="fixture-chip">Deterministic fixtures</span><Button v-if="['overview','experiments'].includes(page)" @click="modal = 'launch'"><Plus :size="16"/>New experiment</Button><Button v-if="['datasets','targets','evaluators'].includes(page)" @click="openCreate(page === 'datasets' ? 'dataset' : page === 'targets' ? 'target' : 'evaluator')"><Plus :size="16"/>Create new</Button></div></div>
  <div v-if="error || queryError" class="error" role="alert">{{ error || (queryError as Error)?.message }}</div><div v-if="notice" class="notice" role="status"><Check :size="15"/>{{ notice }}<button aria-label="Dismiss notification" @click="notice = ''"><X :size="14"/></button></div>
  <div v-if="project.isPending.value" class="empty-state"><h3>Loading your project…</h3></div>
  <template v-else-if="page === 'overview'">
    <section class="overview-banner"><div><span class="eyebrow">YOUR NEXT RELEASE, WITH EVIDENCE</span><h2>Know exactly what changed.</h2><p>{{ project.data.value?.description }}</p><RouterLink :to="`/projects/${projectId}/compare`" class="text-link">Open comparison <ArrowRight :size="16"/></RouterLink></div><div class="banner-diagram"><span><Database :size="18"/>Dataset</span><ArrowRight :size="18"/><span><FlaskConical :size="18"/>Experiment</span><ArrowRight :size="18"/><span class="accent"><GitCompareArrows :size="18"/>Evidence</span></div></section>
    <div class="stat-grid"><article class="stat-card"><span>Experiments</span><strong>{{ project.data.value?.experiments.length || 0 }}</strong><small>Saved execution records</small></article><article class="stat-card"><span>Dataset versions</span><strong>{{ versions('dataset').length }}</strong><small>Immutable snapshots</small></article><article class="stat-card"><span>Latest field accuracy</span><strong>{{ percent(latest.data.value?.summary.metrics.field_accuracy?.mean) }}</strong><small>{{ latest.data.value?.summary.metrics.field_accuracy?.scored || 0 }} scored / {{ latest.data.value?.summary.total || 0 }} executions</small></article><article class="stat-card"><span>Latest coverage</span><strong>{{ percent(latest.data.value?.summary.metrics.field_accuracy?.coverage) }}</strong><small>{{ latest.data.value?.summary.target_errors || 0 }} target errors</small></article></div>
    <div class="two-col"><section class="panel pad"><span class="eyebrow">REPRODUCIBILITY</span><h3>Every run has a fixed reference.</h3><p>Dataset, target adapter, and evaluator suite versions are pinned. Your baseline is captured when a run starts.</p></section><section class="panel pad"><span class="eyebrow">CALIBRATION</span><h3>Keep people in the loop.</h3><p>Review disagreements without rewriting automated judgments.</p><RouterLink :to="`/projects/${projectId}/reviews`" class="text-link">Review cases <ArrowRight :size="14"/></RouterLink></section></div>
  </template>
  <section v-if="['overview','experiments'].includes(page)" class="panel"><div class="panel-header"><h2>{{ page === 'overview' ? 'Recent experiments' : 'Run history' }} <span class="count">{{ project.data.value?.experiments.length || 0 }}</span></h2><span class="muted">Auto-refreshing</span></div><table v-if="project.data.value?.experiments.length"><thead><tr><th>Experiment</th><th>Status</th><th>Mode</th><th>Concurrency</th><th>Created</th></tr></thead><tbody><tr v-for="e in project.data.value.experiments.slice(0,page === 'overview' ? 6 : 100)" :key="e.id"><td><RouterLink :to="`/experiments/${e.id}`" class="strong-link">{{ e.name }}</RouterLink><small class="block mono">{{ e.id.slice(0,8) }}</small></td><td><Status :value="e.status"/></td><td>{{ e.parent_id ? 'Rescore' : e.mode }}</td><td>{{ e.concurrency }}</td><td class="muted">{{ new Date(e.created_at).toLocaleString() }}</td></tr></tbody></table><div v-else class="empty-state"><FlaskConical/><h3>Your first experiment starts here</h3><p>Select a dataset, target, and evaluation suite.</p><Button @click="modal = 'launch'">Launch experiment</Button></div></section>
  <template v-if="['datasets','targets','evaluators'].includes(page)">
    <div v-if="page === 'datasets'" class="info-strip"><ShieldCheck :size="17"/>Held-out datasets protect evaluation validity. Repeated prompt tuning on the same set weakens that evidence.</div>
    <section v-for="kind in (page === 'evaluators' ? ['evaluator','suite'] : [page === 'datasets' ? 'dataset' : 'target'])" :key="kind" class="panel"><div class="panel-header"><h2>{{ kind === 'suite' ? 'Evaluation suites' : kind === 'evaluator' ? 'Evaluator library' : kind === 'dataset' ? 'Versioned datasets' : 'HTTP connections' }} <span class="count">{{ resources(kind).length }}</span></h2><Button v-if="kind === 'suite'" variant="outline" size="sm" @click="openCreate('suite')">New suite</Button></div><table v-if="resources(kind).length"><thead><tr><th>Name</th><th>Latest version</th><th>Configuration</th><th>Actions</th></tr></thead><tbody><tr v-for="r in resources(kind)" :key="r.id"><td><button class="strong-link" @click="openEdit(r)">{{ r.name }}</button><small class="block mono">{{ r.id.slice(0,8) }}</small></td><td><span class="version-badge">v{{ r.versions[0]?.number }}</span> <small>{{ r.versions.length }} saved</small></td><td class="muted"><span v-if="kind === 'dataset'">{{ r.versions[0]?.config.held_out ? 'Held out' : 'Development' }}</span><span v-else-if="kind === 'target'" class="mono">{{ r.versions[0]?.config.endpoint }}</span><span v-else-if="kind === 'evaluator'">{{ human(r.versions[0]?.config.kind || '') }} · {{ r.versions[0]?.config.metric_key }}</span><span v-else>{{ r.versions[0]?.config.evaluator_version_ids.length }} evaluators</span></td><td><div class="inline-actions"><Button variant="outline" size="sm" @click="openEdit(r)">Inspect / version</Button><a v-if="kind === 'dataset'" :href="`/api/versions/${r.versions[0]?.id}/jsonl`" aria-label="Export JSONL"><Download :size="17"/></a><Button v-if="kind === 'target'" variant="outline" size="sm" @click="selectedVersion = r.versions[0]!.id; modal = 'test'; testResult = null">Test</Button></div></td></tr></tbody></table><div v-else class="empty-state"><h3>No {{ kind }} configured</h3><Button @click="openCreate(kind)">Create {{ kind }}</Button></div></section>
  </template>
  <template v-if="page === 'results' && experiment.data.value">
    <div class="experiment-toolbar"><Status :value="experiment.data.value.status"/><span class="mono muted">{{ experimentId.slice(0,8) }}</span><span>{{ experiment.data.value.mode }} · {{ experiment.data.value.concurrency }} concurrent · {{ experiment.data.value.repetitions }} replicate(s) · 0 warm-up</span><div class="spacer"></div><Button v-if="['queued','running'].includes(experiment.data.value.status)" variant="outline" @click="action(() => post(`/experiments/${experimentId}/cancel`), 'Cancellation requested')">Cancel</Button><Button v-if="['failed','partially_failed'].includes(experiment.data.value.status)" variant="outline" @click="action(() => post(`/experiments/${experimentId}/retry`), 'Failed work queued')">Retry failed work</Button><Button v-if="experiment.data.value.status === 'completed'" variant="outline" @click="action(() => post(`/projects/${projectId}/baselines`, { experiment_id: experimentId }), 'Baseline pinned')"><Pin :size="14"/>Pin baseline</Button></div>
    <div class="stat-grid"><article class="stat-card"><span>Executions</span><strong>{{ experiment.data.value.summary.total }}</strong><small>{{ experiment.data.value.summary.execution_states.completed || 0 }} completed</small></article><article class="stat-card"><span>Target errors</span><strong>{{ experiment.data.value.summary.target_errors }}</strong><small>Failures remain in denominators</small></article><article class="stat-card"><span>P95 target latency</span><strong class="smaller">{{ ms(experiment.data.value.summary.target_latency_ms.p95) }}</strong><small>Nearest rank · n={{ experiment.data.value.summary.target_latency_ms.n }}</small></article><article class="stat-card"><span>Target cost</span><strong class="smaller">{{ experiment.data.value.summary.target_cost.total_usd == null ? 'Unavailable' : `$${experiment.data.value.summary.target_cost.total_usd.toFixed(4)}` }}</strong><small>{{ experiment.data.value.summary.target_cost.provenance }}</small></article></div>
    <section class="panel"><div class="panel-header"><h2>Project criteria</h2><span class="muted">No universal aggregate score</span></div><table><thead><tr><th>Metric</th><th>Mean</th><th>Coverage</th><th>Pass / fail</th><th>N/A</th><th>Errors</th><th>Missing</th></tr></thead><tbody><tr v-for="(m,key) in experiment.data.value.summary.metrics" :key="key"><td class="mono">{{ key }}</td><td><strong>{{ percent(m.mean) }}</strong></td><td>{{ m.scored }}/{{ m.denominator }} ({{ percent(m.coverage) }})</td><td>{{ m.passed }} / {{ m.failed }}</td><td>{{ m.not_applicable }}</td><td>{{ m.errors }}</td><td>{{ m.missing }}</td></tr></tbody></table></section>
    <template v-for="(m,key) in experiment.data.value.summary.metrics" :key="String(key)"><section v-if="m.classification" class="panel pad"><h3>{{ key }} · classification metrics</h3><JsonView :value="m.classification"/></section></template>
    <section class="panel"><div class="panel-header"><h2>Case results</h2><select v-model="filter" aria-label="Filter case results"><option value="all">All cases</option><option value="failing">Failing scores</option><option value="errors">Execution errors</option></select></div><table><thead><tr><th>Case / replicate</th><th>Status</th><th>Criteria</th><th>Target latency</th><th>Review</th></tr></thead><tbody><tr v-for="row in filteredRows" :key="row.id"><td><RouterLink :to="`/cases/${row.id}`" class="strong-link mono">{{ row.case_id }} #{{ row.replicate }}</RouterLink><div class="tags"><span v-for="tag in row.case.tags" :key="tag">{{ tag }}</span></div></td><td><Status :value="row.status"/></td><td><span v-for="r in row.results" :key="r.metric_key" class="metric-pill" :class="r.passed ? 'pass' : 'fail'">{{ r.metric_key }} {{ r.score == null ? '—' : percent(r.score) }}</span></td><td class="mono">{{ ms(row.target_latency_ms) }}</td><td>{{ row.reviews.length ? `${row.reviews.length} assessment(s)` : 'Unreviewed' }}</td></tr></tbody></table></section>
    <div class="two-col"><section class="panel pad"><h3>Rescore saved outputs</h3><p>Create a linked evaluation without calling the target again.</p><label>Evaluation suite<select v-model="suiteId"><option v-for="v in versions('suite')" :key="v.id" :value="v.id">{{ v.label }}</option></select></label><Button variant="outline" :disabled="busy || ['queued','running'].includes(experiment.data.value.status)" @click="rescore"><RotateCcw :size="14"/>Rescore outputs</Button></section><section class="panel pad"><h3>Human calibration</h3><p>{{ experiment.data.value.calibration.reviewed_decisions }} reviewed decisions · {{ percent(experiment.data.value.calibration.agreement) }} agreement</p><p>{{ experiment.data.value.calibration.disagreements.length }} disagreements. Automated judgments are preserved.</p><div class="inline-actions"><a class="text-link" :href="`/api/experiments/${experimentId}/report?format=json&metric=field_accuracy`"><Download :size="15"/>JSON report</a><a class="text-link" :href="`/api/experiments/${experimentId}/report?format=junit&metric=field_accuracy`">JUnit</a></div></section></div>
  </template>
  <template v-if="page === 'case' && execution.data.value">
    <div class="experiment-toolbar"><Status :value="execution.data.value.status"/><span>Replicate {{ execution.data.value.replicate }}</span><span>Target {{ ms(execution.data.value.target_latency_ms) }}</span><span>Evaluation {{ ms(execution.data.value.evaluation_latency_ms) }}</span><span v-if="execution.data.value.late_completion" class="warning-chip">Finished after cancellation</span></div><div v-if="execution.data.value.target_error" class="error">{{ execution.data.value.target_error }}</div>
    <div class="two-col"><section class="panel"><div class="panel-header"><h2>Target input</h2></div><JsonView :value="execution.data.value.case.input"/></section><section class="panel"><div class="panel-header"><h2>Actual output</h2></div><JsonView :value="execution.data.value.output" :missing="!execution.data.value.output_present"/></section><section class="panel"><div class="panel-header"><h2>Reference output</h2><small>Evaluator only</small></div><JsonView :value="execution.data.value.case.expected" :missing="!('expected' in execution.data.value.case)"/></section><section class="panel"><div class="panel-header"><h2>Context & criteria</h2><small>Evaluator only</small></div><JsonView :value="{ context: execution.data.value.case.context, acceptance_criteria: execution.data.value.case.acceptance_criteria }"/></section></div>
    <section class="panel"><div class="panel-header"><h2>Evaluator evidence</h2></div><div v-for="r in execution.data.value.results" :key="r.metric_key" class="evaluator-row"><div><strong class="mono">{{ r.metric_key }}</strong><p>{{ r.explanation }}</p><small class="mono">{{ r.evidence.join(', ') }} · version {{ r.evaluator_version.slice(0,8) }}</small></div><Status :value="r.status !== 'scored' ? r.status : r.passed ? 'pass' : 'fail'"/></div></section>
    <div class="two-col"><section class="panel pad"><h3>Observable tool-call trace</h3><JsonView :value="execution.data.value.trace"/><h3>Telemetry & provenance</h3><JsonView :value="execution.data.value.metadata"/></section><section class="panel pad"><h3>Independent human assessment</h3><p>Saving a review preserves the automated judgment.</p><form @submit.prevent="saveReview"><label>Metric<select v-model="reviewMetric"><option v-for="r in execution.data.value.results" :key="r.metric_key">{{ r.metric_key }}</option></select></label><label>Human decision<select v-model="reviewPassed"><option :value="true">Pass</option><option :value="false">Fail</option></select></label><label>Assessment note<textarea v-model="reviewNote" required placeholder="Explain the decision using observable evidence."/></label><Button type="submit" :disabled="busy || !reviewMetric">Save human assessment</Button></form><div v-for="r in execution.data.value.reviews" :key="r.id" class="review-note"><Status :value="r.passed ? 'pass' : 'fail'"/><p>{{ r.note }}</p><small>{{ new Date(r.created_at).toLocaleString() }}</small></div></section></div><section class="panel"><div class="panel-header"><h2>Attempt history</h2><small>First successful target attempt contributes.</small></div><table><thead><tr><th>Phase</th><th>Attempt</th><th>Outcome</th><th>Error</th></tr></thead><tbody><tr v-for="a in execution.data.value.attempts" :key="a.id"><td>{{ a.phase }}</td><td>{{ a.number }}</td><td><Status :value="a.status"/></td><td>{{ a.error || '—' }}</td></tr></tbody></table></section>
  </template>
  <section v-if="page === 'reviews'" class="panel"><div class="panel-header"><h2>Calibration queue <span class="count">{{ displayReviews.length }}</span></h2><label class="check-label"><input v-model="onlyUnreviewed" type="checkbox"/>Unreviewed only</label></div><table v-if="displayReviews.length"><thead><tr><th>Case</th><th>Experiment</th><th>Automated criteria</th><th>Human assessments</th><th></th></tr></thead><tbody><tr v-for="row in displayReviews" :key="row.id"><td class="mono">{{ row.case_id }} #{{ row.replicate }}</td><td>{{ row.experiment_name }}</td><td><span v-for="r in row.results" :key="r.metric_key" class="metric-pill" :class="r.passed ? 'pass' : 'fail'">{{ r.metric_key }}</span></td><td>{{ row.reviews.length }}</td><td><RouterLink :to="`/cases/${row.id}`" class="text-link">Review <ArrowRight :size="15"/></RouterLink></td></tr></tbody></table><div v-else class="empty-state"><Check/><h3>No cases waiting for review</h3><p>Completed experiments populate this queue.</p></div></section>
  <div v-if="page === 'gates'" class="two-col"><section class="panel pad"><h3>Release policy</h3><p>Coverage and evaluator errors have explicit failure policies.</p><label>Gate configuration<textarea v-model="gateText" class="code-editor" rows="18"/></label><Button :disabled="busy" @click="action(() => api(`/projects/${projectId}/gate`, { method: 'PUT', body: JSON.stringify(JSON.parse(gateText)) }), 'Gate policy saved')">Save gate policy</Button></section><section class="panel pad"><h3>Evaluate a release</h3><label>Experiment<select v-model="gateExperiment"><option v-for="e in project.data.value?.experiments" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><label>Comparison metric<input v-model="metric"/></label><Button :disabled="!gateExperiment || busy" @click="action(async () => { gateResult = await api(`/experiments/${gateExperiment}/gate?metric=${encodeURIComponent(metric)}`) }, 'Gate evaluated')"><ShieldCheck :size="16"/>Evaluate gate</Button><div v-if="gateResult" class="gate-result" :class="gateResult.passed ? 'pass' : 'fail'"><h3>{{ gateResult.passed ? 'Gate passed' : gateResult.exit_code === 2 ? 'Infrastructure / configuration error' : 'Quality gate failed' }}</h3><p>Exit code {{ gateResult.exit_code }}</p><ul><li v-for="reason in [...gateResult.quality_failures,...gateResult.infrastructure_errors]" :key="reason">{{ reason }}</li></ul><small class="mono">Pinned baseline: {{ gateResult.pinned_baseline_id || 'none' }}</small></div><div v-if="gateExperiment" class="inline-actions report-actions"><a class="text-link" :href="`/api/experiments/${gateExperiment}/report?format=json&metric=${metric}`"><Download :size="15"/>JSON</a><a class="text-link" :href="`/api/experiments/${gateExperiment}/report?format=junit&metric=${metric}`">JUnit</a><Button variant="outline" size="sm" @click="action(() => post(`/experiments/${gateExperiment}/artifacts?metric=${metric}`), 'Report snapshot persisted')">Save snapshot</Button></div><h3>CI command</h3><pre class="json-view">evaldock gate {{ gateExperiment || '&lt;experiment-id&gt;' }} --metric {{ metric }}</pre></section></div>
  <template v-if="page === 'settings'"><div class="two-col"><section class="panel pad"><h3>Server-side credentials</h3><p>Encrypted with the application key. Saved values are masked.</p><div v-for="c in settingsData.data.value?.credentials" :key="c.id" class="credential-row"><strong>{{ c.name }}</strong><span>{{ c.value }}</span><small class="mono">{{ c.id }}</small></div><form @submit.prevent="createSecret"><label>Name<input v-model="secretName" required/></label><label>Secret<input v-model="secretValue" type="password" autocomplete="new-password" required/></label><Button type="submit" :disabled="busy">Save credential</Button></form></section><section class="panel pad"><h3>Scoped API tokens</h3><form @submit.prevent="createToken"><label>Token name<input v-model="tokenName" required/></label><p>Scope: read & write in this workspace. Expiry: 30 days.</p><Button type="submit" :disabled="busy">Create token</Button></form><pre v-if="newToken" class="json-view">{{ newToken }}</pre><div v-for="t in settingsData.data.value?.tokens" :key="t.id" class="credential-row"><span>{{ t.name }} · {{ t.scopes.join(', ') }}</span><small>{{ t.revoked ? 'Revoked' : 'Active' }}</small><Button v-if="!t.revoked" size="sm" variant="outline" @click="action(() => api(`/tokens/${t.id}`, { method: 'DELETE' }), 'Token revoked')">Revoke</Button></div></section></div><section class="panel pad"><h3>Workspace membership</h3><table><thead><tr><th>Member</th><th>Email</th><th>Role</th></tr></thead><tbody><tr v-for="m in settingsData.data.value?.members" :key="m.id"><td>{{ m.name }}</td><td>{{ m.email }}</td><td>{{ m.role }}</td></tr></tbody></table><form class="member-form" @submit.prevent="action(async () => { await post(`/workspaces/${project.data.value?.workspace_id}/members`, member); member.password = '' }, 'Workspace member added')"><label>Name<input v-model="member.name" required/></label><label>Email<input v-model="member.email" type="email" required/></label><label>Initial password<input v-model="member.password" type="password" minlength="12" required/></label><label>Role<select v-model="member.role"><option>viewer</option><option>editor</option><option>owner</option></select></label><Button type="submit">Add member</Button></form></section><section class="panel"><div class="panel-header"><h2>Audit events</h2></div><table><thead><tr><th>Action</th><th>Time</th><th>Record</th></tr></thead><tbody><tr v-for="a in settingsData.data.value?.audit" :key="a.id"><td>{{ a.action }}</td><td>{{ new Date(a.created_at).toLocaleString() }}</td><td class="mono">{{ JSON.stringify(a.detail) }}</td></tr></tbody></table></section><Button variant="outline" @click="modal = 'project'; formName = ''">Create another project</Button></template>
  <div v-if="modal" class="modal-overlay" @click.self="modal = ''" @keydown.esc="modal = ''"><section role="dialog" aria-modal="true" :aria-label="modal === 'launch' ? 'Launch experiment' : 'Configuration editor'" class="modal"><div class="panel-header"><h2>{{ modal === 'launch' ? 'Launch experiment' : modal === 'resource' ? selectedResource ? 'Create a new version' : `New ${editorKind}` : modal === 'test' ? 'Test target connection' : 'New project' }}</h2><button aria-label="Close dialog" @click="modal = ''"><X :size="20"/></button></div><div class="modal-body"><div v-if="error" class="error" role="alert">{{ error }}</div>
    <form v-if="modal === 'launch'" @submit.prevent="launchExperiment"><label>Experiment name<input v-model="launchName" placeholder="e.g. Prompt v3 · candidate"/></label><label>Dataset version<select v-model="datasetId" required><option v-for="v in versions('dataset')" :key="v.id" :value="v.id">{{ v.label }}</option></select></label><label>Execution mode<select v-model="launchMode"><option value="http">HTTP target</option><option value="imported">Imported outputs</option></select></label><label v-if="launchMode === 'http'">Target version<select v-model="targetId" required><option v-for="v in versions('target')" :key="v.id" :value="v.id">{{ v.label }}</option></select></label><label v-else>Imported outputs (JSON array, case_id + replicate + output)<textarea v-model="imported" class="code-editor" rows="8"/></label><label>Evaluation suite<select v-model="suiteId" required><option v-for="v in versions('suite')" :key="v.id" :value="v.id">{{ v.label }}</option></select></label><div class="two-col"><label>Repetitions<input v-model="repetitions" type="number" min="1" max="20" required/></label><label>Concurrency<input v-model="concurrency" type="number" min="1" max="16" required/></label></div><label v-if="launchMode === 'http'">Optional target call budget<input v-model="budget" type="number" min="1" placeholder="Unlimited"/></label><p class="muted">The main baseline is pinned now. Only case input is sent to targets. Use test endpoints: target calls may have side effects.</p><Button type="submit" :disabled="busy || !datasetId || !suiteId"><Play :size="15"/>{{ busy ? 'Launching…' : 'Launch experiment' }}</Button></form>
    <form v-else-if="modal === 'resource'" @submit.prevent="saveResource"><label>Name<input v-model="formName" :disabled="!!selectedResource" required/></label><label v-if="selectedResource">Inspect version<select v-model="selectedVersion"><option v-for="v in selectedResource.versions" :key="v.id" :value="v.id">v{{ v.number }} · {{ v.fingerprint.slice(0,12) }}</option></select></label><p class="muted">Existing versions are immutable. Saving creates a new version.</p><details v-if="editorKind === 'dataset'"><summary>Import JSONL with line-by-line validation</summary><label>JSONL content<textarea v-model="importText" class="code-editor" rows="6"/></label><Button type="button" variant="outline" @click="previewImport">Validate & preview</Button><JsonView v-if="preview" :value="{ count: preview.count, errors: preview.errors, preview: preview.preview.slice(0,2) }"/></details><p v-if="editorKind === 'evaluator'" class="info-strip">Kinds: json_schema, exact_match, field_comparison, numeric_tolerance, classification, tool_calls, llm_judge. Live judging requires a credential and versioned rubric.</p><div v-if="editorKind === 'suite'" class="hint-list"><small v-for="v in versions('evaluator')" :key="v.id">{{ v.label }} <code>{{ v.id }}</code></small></div><label>Version content<textarea v-model="editor" class="code-editor" rows="18" spellcheck="false" required/></label><Button type="submit" :disabled="busy || !editor">Save immutable version</Button></form>
    <form v-else-if="modal === 'test'" @submit.prevent="action(async () => { testResult = await post(`/targets/${selectedVersion}/test`, { input: JSON.parse(testInput) }) }, 'Connection test completed')"><p>This sends one real request to the configured test endpoint.</p><label>Target input JSON<textarea v-model="testInput" class="code-editor" rows="10"/></label><Button type="submit" :disabled="busy">Send test request</Button><JsonView v-if="testResult" :value="testResult"/></form>
    <form v-else @submit.prevent="action(async () => { const p = await post<Project>('/projects', { name: formName, workspace_id: project.data.value?.workspace_id }); modal = ''; router.push(`/projects/${p.id}/overview`) }, 'Project created')"><label>Project name<input v-model="formName" required/></label><Button type="submit">Create project</Button></form>
  </div></section></div>
</main>
</template>
